### ISSUE TITLE
offer prometheuses.defaultSampleLimit (additionally to enforcedSampleLimit)

### ISSUE THREAD

**Issue by mblaschke-daimlertruck** [prometheus-operator/prometheus-operator#5119] opened 2022-10-25 14:33 UTC
**What is missing?**
Please provide a `defaultSampleLimit` in `Prometheuses` spec which should be used as default value if `PodMonitor` or `ServiceMonitor` doesn't have a `sampleLimit`.

**Why do we need it?**
In shared clusters we cannot control that `sampleLimit` is in place.
`enforcedSampleLimit` might be an option but some metric jobs needs higher limits and `enforcedSampleLimit` only sets the default and upper limit for `sampleLimit`. We would like to set only the default without any upper limit (or the upper limit should be a different limit)

eg:

`defaultSampleLimit: 100000`
`enforcedSampleLimit: 1000000`

**Environment**
Azure AKS

* Prometheus Operator version:
v0.59.1

**Anything else we need to know?**:

**Comment by mblaschke-daimlertruck** [comment] 2022-10-25 16:46
would be still good to have it in both services (different scopes)

**Comment by mblaschke** [comment] 2022-10-25 19:19
@simonpasquier added a draft PR, not sure if that's everything what i have to do here

**Comment by simonpasquier** [comment] 2022-10-26 07:23
> would be still good to have it in both services (different scopes)

I agree but I'd prefer to hear from Prometheus first so we don't end up with different approaches... Could you file an issue to github.com/prometheus/prometheus?

**Comment by simonpasquier** [comment] 2023-06-16 15:44
Duplicate of #5638

**Closed by simonpasquier** 2023-06-16 15:44 UTC
Labels: help wanted, kind/feature
