### ISSUE TITLE
Cannot fire cluster-wide alerts from default AlertManagerConfig

### ISSUE THREAD

**Issue by nickytd** [prometheus-operator/prometheus-operator#3900] opened 2021-03-06 10:01 UTC
Hi,

when AlertManagerConfig resource is used it adds a namespace matcher to the root route, which effectively stops propagation of the alerts down the tree.
...

List of matchers that the alert’s labels should match. For the first level route, the operator removes any existing equality and regexp matcher on the namespace label and adds a namespace: <object namespace> matcher.

...

Should there be a configuration option or even better removed from the root?

Thanks
Niki

**Comment by simonpasquier** [comment] 2021-03-08 11:16
Closed as duplicate of #3737

**Closed by simonpasquier** 2021-03-08 11:16 UTC
Labels: kind/bug
