### ISSUE TITLE
No way to mount secrets to thanos sidecar to enable tls

### ISSUE THREAD

**Issue by mengqhai** [prometheus-operator/prometheus-operator#3322] opened 2020-07-07 15:45 UTC
**What happened?**
To enable tls for thanos sidecar, I'll need to config grpcServerTlsConfig in ThanosSpec.  And in the [doc of ThanosSpec](https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#thanosspec), it says:
```
Note: Currently only the CAFile, CertFile, and KeyFile fields are supported. Maps to the '--grpc-server-tls-*' CLI args.
```
So I'll need a way to mount the tls related secrets into the thanos sidecar container as CAFile, CertFile, and KeyFile.  However there's no way to do so in ThanosSpec and this makes it impossible to config grpcServerTlsConfig for the sidecar.

**Did you expect to see something different?**
There should be some way to mount secrets for thanos sidecar.

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**

* Prometheus Operator version:

    v0.38.1

* Kubernetes version information:

    v1.14.8

**Comment by brancz** [comment] 2020-07-08 08:23
This is not a bug, this is a feature/enhancement request. You can add mounts by merging through the containers array, but I agree that the secret/configmap key references would be better here. If you want to give this a stab, the contribution would be more than welcome! :)

**Comment by simonpasquier** [comment] 2022-09-21 13:23
Unless I'm mistaken, it's closed by https://github.com/prometheus-operator/prometheus-operator/pull/4238.

**Closed by simonpasquier** 2022-09-21 13:23 UTC
Labels: kind/feature
