### ISSUE TITLE
Rule evaluation failures for alertmanager.rules

### ISSUE THREAD

**Issue by bgagnon** [prometheus-operator/prometheus-operator#1319] opened 2018-05-08 19:15 UTC
Two of the `kube-prometheus` rules from `alertmanager.rules` fail to evaluate: `AlertmanagerConfigInconsistent` and `AlertmanagerDownOrMissing`.

The error message is `many-to-many matching not allowed: matching labels must be unique on one side`.

Here are the full log entries:

```
level=warn
ts=2018-05-08T19:09:30.012163531Z
caller=manager.go:339
component="rule manager"
group=alertmanager.rules
msg="Evaluating rule failed"
rule="alert: AlertmanagerConfigInconsistent\nexpr: count_values by(service) (\"config_hash\", alertmanager_config_hash) / on(service)\n  group_left() label_replace(prometheus_operator_alertmanager_spec_replicas, \"service\",\n  \"alertmanager-$1\", \"alertmanager\", \"(.*)\") != 1\nfor: 5m\nlabels:\n  severity: critical\nannotations:\n  description: The configuration of the instances of the Alertmanager cluster `{{$labels.service}}`\n    are out of sync.\n  summary: Configuration out of sync\n" err="many-to-many matching not allowed: matching labels must be unique on one side"
```
and:
```
level=warn
ts=2018-05-08T19:09:30.013795976Z
caller=manager.go:339
component="rule manager"
group=alertmanager.rules
msg="Evaluating rule failed"
rule="alert: AlertmanagerDownOrMissing\nexpr: label_replace(prometheus_operator_alertmanager_spec_replicas, \"job\", \"alertmanager-$1\",\n  \"alertmanager\", \"(.*)\") / on(job) group_right() sum by(job) (up) != 1\nfor: 5m\nlabels:\n  severity: warning\nannotations:\n  description: An unexpected number of Alertmanagers are scraped or Alertmanagers\n    disappeared from discovery.\n  summary: Alertmanager down or missing\n" err="many-to-many matching not allowed: matching labels must be unique on one side"
```

**Comment by bgagnon** [comment] 2018-05-08 20:59
I wish I knew how to fix this and submit a PR... but my PromQL is weak at best :/ I _think_ the issue is with the `group_right()` clause, but I'm not sure what the problem is exactly.

**Comment by nabadger** [comment] 2018-07-31 10:18
@bgagnon did you manage to resolve this in the end? 

We are hitting this as well.

It seems to be related to `prometheus_operator_alertmanager_spec_replicas` 

If I just query this in prometheus I get 2 rows back. I'm not sure the 1st row is expected, and I don't know why it's `exported_namespace` = `default`, although I suspect we created a `prometheusrule` in that namespace once (but deleted it). Everything else we do regarding prometheus-operator is in it's own `monitoring` namespace.

```

prometheus_operator_alertmanager_spec_replicas{alertmanager="main",endpoint="http",exported_namespace="default",instance="10.244.8.64:8080",job="prometheus-operator",namespace="monitoring",pod="prometheus-operator-75d55576c5-psctp",service="prometheus-operator"} | 1


prometheus_operator_alertmanager_spec_replicas{alertmanager="main",endpoint="http",exported_namespace="monitoring",instance="10.244.8.64:8080",job="prometheus-operator",namespace="monitoring",pod="prometheus-operator-75d55576c5-psctp",service="prometheus-operator"} | 3


```

**Comment by brancz** [comment] 2018-07-31 11:19
You're right, the alerting rule is incorrect, it could be `by(service, namespace)` and `on(service, namespace)`. The error is currently happening because there are multiple matches when there should be a single one.

**Comment by nabadger** [comment] 2018-07-31 11:41
I actually still hit the issue by when joining by `service` and `namespace`, both rows still get returned since those values do match.

I'm still not sure where the extra row is coming from though with `exported_namespace="default"`

**Comment by brancz** [comment] 2018-07-31 11:46
Ah I see. That's a configuration mistake. We should be setting `honor_labels: true` in the Prometheus Operator's `ServiceMonitor`.

**Comment by nabadger** [comment] 2018-07-31 12:10
That looks like it resolved it :)

I've added `honorLabels: true` to the `ServiceMonitor` for the Prometheus Operator.

If I use the following query I believe it works (it at least does not throw an error):
```
count_values("config_hash", alertmanager_config_hash) BY (service, namepace) / ON(service, namespace)
      GROUP_LEFT() label_replace(prometheus_operator_alertmanager_spec_replicas, "service",
      "alertmanager-$1", "alertmanager", "(.*)") != 1
  ```

And looking at just`prometheus_operator_alertmanager_spec_replicas` we now get:

```
prometheus_operator_alertmanager_spec_replicas{alertmanager="main",endpoint="http",instance="10.244.6.77:8080",job="prometheus-operator",namespace="default",pod="prometheus-operator-6d8b59f667-x5pms",service="prometheus-operator"} | 1

prometheus_operator_alertmanager_spec_replicas{alertmanager="main",endpoint="http",instance="10.244.6.77:8080",job="prometheus-operator",namespace="monitoring",pod="prometheus-operator-6d8b59f667-x5pms",service="prometheus-operator"} | 3
```

**Comment by brancz** [comment] 2018-07-31 13:15
@nabadger would you like to open a PR to fix these? :slightly_smiling_face:

**Comment by nabadger** [comment] 2018-07-31 14:33
Will do

**Comment by nabadger** [comment] 2018-07-31 15:11
Just a bit more information I found. The cause of this problem (for my case) was that we had multiple `Alertmanager` CRD's installed. 

Typically we install 1 into the `monitoring` namespace, but it looks like we installed one into the `default` namespace as well (probably an accident as it's a test cluster). 

This probably is not a common scenario within a single cluster, but at least explains why we were getting 2 rows.

**Comment by brancz** [comment] 2018-07-31 15:26
It's definitely feasible to have multiple `Alertmanager` objects, so this should not be causing a problem.

**Comment by onedr0p** [comment] 2020-06-06 13:39
Year 2020 making a call to see if there's any progress on this. I am getting this even on the latest chart version.

**Comment by brancz** [comment] 2020-06-09 11:24
cc @simonpasquier I think you recently fixed a bunch of these, were these rules also fixed in that?

**Comment by BlackBsd** [comment] 2020-09-24 21:03
Hello,
I recently switched from using the stable/prometheus-operator helm chart to the prometheus-community/charts/kube-prometheus-stack and I am now seeing this problem as well.  Its not really complaining about alertmanager, rather something about kubelet.

`
level=warn ts=2020-09-24T20:31:49.382Z caller=manager.go:577 component="rule manager" group=kubernetes-system-kubelet msg="Evaluating rule failed" rule="alert: KubeletPodStartUpLatencyHigh\nexpr: histogram_quantile(0.99, sum by(instance, le) (rate(kubelet_pod_worker_duration_seconds_bucket{job=\"kubelet\",metrics_path=\"/metrics\"}[5m])))\n  * on(instance) group_left(node) kubelet_node_name{job=\"kubelet\",metrics_path=\"/metrics\"}\n  > 60\nfor: 15m\nlabels:\n  severity: warning\nannotations:\n  message: Kubelet Pod startup 99th percentile latency is {{ $value }} seconds on\n    node {{ $labels.node }}.\n  runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubeletpodstartuplatencyhigh\n" err="found duplicate series for the match group {instance=\"10.31.5.101:10250\"} on the right hand-side of the operation: [{__name__=\"kubelet_node_name\", endpoint=\"https-metrics\", instance=\"10.31.5.101:10250\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"kube-system\", node=\"ip-10-31-5-101.ec2.internal\", service=\"monitoring-dev-kube-promet-kubelet\"}, {__name__=\"kubelet_node_name\", endpoint=\"https-metrics\", instance=\"10.31.5.101:10250\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"kube-system\", node=\"ip-10-31-5-101.ec2.internal\", service=\"prometheus-dev-kube-promet-kubelet\"}];many-to-many matching not allowed: matching labels must be unique on one side"
level=warn ts=2020-09-24T20:31:51.973Z caller=manager.go:577 component="rule manager" group=kubelet.rules msg="Evaluating rule failed" rule="record: node_quantile:kubelet_pleg_relist_duration_seconds:histogram_quantile\nexpr: histogram_quantile(0.99, sum by(instance, le) (rate(kubelet_pleg_relist_duration_seconds_bucket[5m]))\n  * on(instance) group_left(node) kubelet_node_name{job=\"kubelet\",metrics_path=\"/metrics\"})\nlabels:\n  quantile: \"0.99\"\n" err="found duplicate series for the match group {instance=\"10.31.5.101:10250\"} on the right hand-side of the operation: [{__name__=\"kubelet_node_name\", endpoint=\"https-metrics\", instance=\"10.31.5.101:10250\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"kube-system\", node=\"ip-10-31-5-101.ec2.internal\", service=\"monitoring-dev-kube-promet-kubelet\"}, {__name__=\"kubelet_node_name\", endpoint=\"https-metrics\", instance=\"10.31.5.101:10250\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"kube-system\", node=\"ip-10-31-5-101.ec2.internal\", service=\"prometheus-dev-kube-promet-kubelet\"}];many-to-many matching not allowed: matching labels must be unique on one side"
level=warn ts=2020-09-24T20:31:51.978Z caller=manager.go:577 component="rule manager" group=kubelet.rules msg="Evaluating rule failed" rule="record: node_quantile:kubelet_pleg_relist_duration_seconds:histogram_quantile\nexpr: histogram_quantile(0.9, sum by(instance, le) (rate(kubelet_pleg_relist_duration_seconds_bucket[5m]))\n  * on(instance) group_left(node) kubelet_node_name{job=\"kubelet\",metrics_path=\"/metrics\"})\nlabels:\n  quantile: \"0.9\"\n" err="found duplicate series for the match group {instance=\"10.31.5.101:10250\"} on the right hand-side of the operation: [{__name__=\"kubelet_node_name\", endpoint=\"https-metrics\", instance=\"10.31.5.101:10250\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"kube-system\", node=\"ip-10-31-5-101.ec2.internal\", service=\"monitoring-dev-kube-promet-kubelet\"}, {__name__=\"kubelet_node_name\", endpoint=\"https-metrics\", instance=\"10.31.5.101:10250\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"kube-system\", node=\"ip-10-31-5-101.ec2.internal\", service=\"prometheus-dev-kube-promet-kubelet\"}];many-to-many matching not allowed: matching labels must be unique on one side"
level=warn ts=2020-09-24T20:31:51.982Z caller=manager.go:577 component="rule manager" group=kubelet.rules msg="Evaluating rule failed" rule="record: node_quantile:kubelet_pleg_relist_duration_seconds:histogram_quantile\nexpr: histogram_quantile(0.5, sum by(instance, le) (rate(kubelet_pleg_relist_duration_seconds_bucket[5m]))\n  * on(instance) group_left(node) kubelet_node_name{job=\"kubelet\",metrics_path=\"/metrics\"})\nlabels:\n  quantile: \"0.5\"\n" err="found duplicate series for the match group {instance=\"10.31.5.101:10250\"} on the right hand-side of the operation: [{__name__=\"kubelet_node_name\", endpoint=\"https-metrics\", instance=\"10.31.5.101:10250\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"kube-system\", node=\"ip-10-31-5-101.ec2.internal\", service=\"monitoring-dev-kube-promet-kubelet\"}, {__name__=\"kubelet_node_name\", endpoint=\"https-metrics\", instance=\"10.31.5.101:10250\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"kube-system\", node=\"ip-10-31-5-101.ec2.internal\", service=\"prometheus-dev-kube-promet-kubelet\"}];many-to-many matching not allowed: matching labels must be unique on one side"
`

The query that is being used for the alert that's firing is: alertname="PrometheusRuleFailures"
`
increase(prometheus_rule_evaluation_failures_total{job="monitoring-dev-kube-promet-prometheus",namespace="monitoring"}[5m]) > 0
`

**Comment by simonpasquier** [comment] 2020-09-25 13:12
`AlertmanagerConfigInconsistent` has been updated in https://github.com/prometheus-operator/kube-prometheus/pull/576 and it shouldn't trigger `many-to-many matching not allowed` errors anymore. AFAICT `AlertmanagerDownOrMissing` has been removed too so I'm closing the issue.

**Closed by simonpasquier** 2020-09-25 13:12 UTC
Labels: kind/bug

**Comment by thodquach** [comment] 2021-03-02 09:33
> Hello,
> I recently switched from using the stable/prometheus-operator helm chart to the prometheus-community/charts/kube-prometheus-stack and I am now seeing this problem as well. Its not really complaining about alertmanager, rather something about kubelet.
> 
> ```
> level=warn ts=2020-09-24T20:31:49.382Z caller=manager.go:577 component="rule manager" group=kubernetes-system-kubelet msg="Evaluating rule failed" rule="alert: KubeletPodStartUpLatencyHigh\nexpr: histogram_quantile(0.99, sum by(instance, le) (rate(kubelet_pod_worker_duration_seconds_bucket{job=\"kubelet\",metrics_path=\"/metrics\"}[5m])))\n  * on(instance) group_left(node) kubelet_node_name{job=\"kubelet\",metrics_path=\"/metrics\"}\n  > 60\nfor: 15m\nlabels:\n  severity: warning\nannotations:\n  message: Kubelet Pod startup 99th percentile latency is {{ $value }} seconds on\n    node {{ $labels.node }}.\n  runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubeletpodstartuplatencyhigh\n" err="found duplicate series for the match group {instance=\"10.31.5.101:10250\"} on the right hand-side of the operation: [{__name__=\"kubelet_node_name\", endpoint=\"https-metrics\", instance=\"10.31.5.101:10250\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"kube-system\", node=\"ip-10-31-5-101.ec2.internal\", service=\"monitoring-dev-kube-promet-kubelet\"}, {__name__=\"kubelet_node_name\", endpoint=\"https-metrics\", instance=\"10.31.5.101:10250\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"kube-system\", node=\"ip-10-31-5-101.ec2.internal\", service=\"prometheus-dev-kube-promet-kubelet\"}];many-to-many matching not allowed: matching labels must be unique on one side"
> level=warn ts=2020-09-24T20:31:51.973Z caller=manager.go:577 component="rule manager" group=kubelet.rules msg="Evaluating rule failed" rule="record: node_quantile:kubelet_pleg_relist_duration_seconds:histogram_quantile\nexpr: histogram_quantile(0.99, sum by(instance, le) (rate(kubelet_pleg_relist_duration_seconds_bucket[5m]))\n  * on(instance) group_left(node) kubelet_node_name{job=\"kubelet\",metrics_path=\"/metrics\"})\nlabels:\n  quantile: \"0.99\"\n" err="found duplicate series for the match group {instance=\"10.31.5.101:10250\"} on the right hand-side of the operation: [{__name__=\"kubelet_node_name\", endpoint=\"https-metrics\", instance=\"10.31.5.101:10250\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"kube-system\", node=\"ip-10-31-5-101.ec2.internal\", service=\"monitoring-dev-kube-promet-kubelet\"}, {__name__=\"kubelet_node_name\", endpoint=\"https-metrics\", instance=\"10.31.5.101:10250\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"kube-system\", node=\"ip-10-31-5-101.ec2.internal\", service=\"prometheus-dev-kube-promet-kubelet\"}];many-to-many matching not allowed: matching labels must be unique on one side"
> level=warn ts=2020-09-24T20:31:51.978Z caller=manager.go:577 component="rule manager" group=kubelet.rules msg="Evaluating rule failed" rule="record: node_quantile:kubelet_pleg_relist_duration_seconds:histogram_quantile\nexpr: histogram_quantile(0.9, sum by(instance, le) (rate(kubelet_pleg_relist_duration_seconds_bucket[5m]))\n  * on(instance) group_left(node) kubelet_node_name{job=\"kubelet\",metrics_path=\"/metrics\"})\nlabels:\n  quantile: \"0.9\"\n" err="found duplicate series for the match group {instance=\"10.31.5.101:10250\"} on the right hand-side of the operation: [{__name__=\"kubelet_node_name\", endpoint=\"https-metrics\", instance=\"10.31.5.101:10250\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"kube-system\", node=\"ip-10-31-5-101.ec2.internal\", service=\"monitoring-dev-kube-promet-kubelet\"}, {__name__=\"kubelet_node_name\", endpoint=\"https-metrics\", instance=\"10.31.5.101:10250\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"kube-system\", node=\"ip-10-31-5-101.ec2.internal\", service=\"prometheus-dev-kube-promet-kubelet\"}];many-to-many matching not allowed: matching labels must be unique on one side"
> level=warn ts=2020-09-24T20:31:51.982Z caller=manager.go:577 component="rule manager" group=kubelet.rules msg="Evaluating rule failed" rule="record: node_quantile:kubelet_pleg_relist_duration_seconds:histogram_quantile\nexpr: histogram_quantile(0.5, sum by(instance, le) (rate(kubelet_pleg_relist_duration_seconds_bucket[5m]))\n  * on(instance) group_left(node) kubelet_node_name{job=\"kubelet\",metrics_path=\"/metrics\"})\nlabels:\n  quantile: \"0.5\"\n" err="found duplicate series for the match group {instance=\"10.31.5.101:10250\"} on the right hand-side of the operation: [{__name__=\"kubelet_node_name\", endpoint=\"https-metrics\", instance=\"10.31.5.101:10250\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"kube-system\", node=\"ip-10-31-5-101.ec2.internal\", service=\"monitoring-dev-kube-promet-kubelet\"}, {__name__=\"kubelet_node_name\", endpoint=\"https-metrics\", instance=\"10.31.5.101:10250\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"kube-system\", node=\"ip-10-31-5-101.ec2.internal\", service=\"prometheus-dev-kube-promet-kubelet\"}];many-to-many matching not allowed: matching labels must be unique on one side"
> ```
> 
> The query that is being used for the alert that's firing is: alertname="PrometheusRuleFailures"
> 
> ```
> increase(prometheus_rule_evaluation_failures_total{job="monitoring-dev-kube-promet-prometheus",namespace="monitoring"}[5m]) > 0
> ```
> 
> **Edit Update**
> I noticed that i had an extra kubelet service still left around from the old chart??
> 
> ```
> # kubectl -n kube-system get services | grep kubelet
> NAME                                   TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)                        AGE
> kube-dns                               ClusterIP   172.20.0.10   <none>        53/UDP,53/TCP                  59d
> monitoring-dev-kube-promet-kubelet     ClusterIP   None          <none>        10250/TCP,10255/TCP,4194/TCP   28h
> monitoring-dev-prometheus-kubelet      ClusterIP   None          <none>        10250/TCP,10255/TCP,4194/TCP   2d5h
> ```
> 
> After removing this service, my problem seemed to have went away.

This fix for me, Tks

**Comment by gmodzelewski** [comment] 2021-05-19 12:20
Hello,

Unfortunately this issue happened again, after installing the kube-prometheus-stack version 14.5.100 in rancher k3s via helm crd. Don't know exactly if the extra service was installed at initial installation or in an upgrade installation afterwards when I changed quotas and limits.

# kubectl -n kube-system get services | grep kubelet

rancher-monitoring-kubelet                  ClusterIP      None           <none>            10250/TCP,10255/TCP,4194/TCP   7d20h
rancher-monitoring-kube-pr-kubelet   ClusterIP      None           <none>            10250/TCP,10255/TCP,4194/TCP   7d20h

Which one do I have to remove? The second one with kube-pr-kubelet in the name?
