### ISSUE TITLE
Enabling Rolebinding for Prometheus Server instead of ClusterRoleBinding

### ISSUE THREAD

**Issue by vperi1730** [prometheus-operator/prometheus-operator#3543] opened 2020-09-24 15:33 UTC
**What did you do?**

We have a use case with the following configuration. Looking out for answers for 1 and 5 asks.

1) Prometheus and Prometheus operators are with role binding.
  a) Rolebinding with Prometheus is resulting in few errors inside the server logs.
User \"system:serviceaccount:brcm-prometheus1:prometheus\" cannot list resource \"nodes\" in API group \"\" at the cluster scope"
level=error ts=2020-09-24T14:15:12.298Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:361: Failed to list *v1.Endpoints: endpoints is forbidden: User \"system:serviceaccount:brcm-prometheus1:prometheus\" cannot list resource \"endpoints\" in API group \"\" at the cluster scope"
level=error ts=2020-09-24T14:15:23.043Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:363: Failed to list *v1.Pod: pods is forbidden: User \"system:serviceaccount:brcm-prometheus1:prometheus\" cannot list resource \"pods\" in API group \"\" at the cluster scope"
level=error ts=2020-09-24T14:15:25.950Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:385: Failed to list *v1.Pod: pods is forbidden: User \"system:serviceaccount:brcm-prometheus1:prometheus\" cannot list resource \"pods\" in API group \"\" at the cluster scope"
level=error ts=2020-09-24T14:15:38.920Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:362: Failed to list *v1.Service: services is forbidden: User \"system:serviceaccount:brcm-prometheus1:prometheus\" cannot list resource \"services\" in API group \"\" at the cluster scope"
level=error ts=2020-09-24T14:15:53.579Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:449: Failed to list *v1.Node: nodes is forbidden: User \"system:serviceaccount:brcm-prometheus1:prometheus\" cannot list resource \"nodes\" in API group \"\" at the cluster scope"
level=error ts=2020-09-24T14:16:01.056Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:361: Failed to list *v1.Endpoints: endpoints is forbidden: User \"system:serviceaccount:brcm-prometheus1:prometheus\" cannot list resource \"endpoints\" in API group \"\" at the cluster scope"

We don't want to use the cluster role binding, how do we resolve this?

2) My Prometheus operator should watch my Prometheus within a namespace.
3) However, my Prometheus server should watch for all the service monitors of diff namespaces.
4) Servicemonitor should collect metrics from the application deployed in diff namespaces. (here we are using namespace selector in the service monitor CR).
5) When we change role bindings to cluster role bindings of the Prometheus server, then we are able to see all metrics of the application across all the namespaces. How to limit this to a defined namespace?

**Did you expect to see some different?**

**Environment**

* Prometheus Operator version: 0.41.1

    `Insert image tag or Git SHA here`
    

* Kubernetes version information:

    `kubectl version`
    

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
level=error ts=2020-09-24T14:14:56.607Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:362: Failed to list *v1.Service: services is forbidden: User \"system:serviceaccount:brcm-prometheus1:prometheus\" cannot list resource \"services\" in API group \"\" at the cluster scope"
level=error ts=2020-09-24T14:15:10.530Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:449: Failed to list *v1.Node: nodes is forbidden: User \"system:serviceaccount:brcm-prometheus1:prometheus\" cannot list resource \"nodes\" in API group \"\" at the cluster scope"
level=error ts=2020-09-24T14:15:12.298Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:361: Failed to list *v1.Endpoints: endpoints is forbidden: User \"system:serviceaccount:brcm-prometheus1:prometheus\" cannot list resource \"endpoints\" in API group \"\" at the cluster scope"
level=error ts=2020-09-24T14:15:23.043Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:363: Failed to list *v1.Pod: pods is forbidden: User \"system:serviceaccount:brcm-prometheus1:prometheus\" cannot list resource \"pods\" in API group \"\" at the cluster scope"
level=error ts=2020-09-24T14:15:25.950Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:385: Failed to list *v1.Pod: pods is forbidden: User \"system:serviceaccount:brcm-prometheus1:prometheus\" cannot list resource \"pods\" in API group \"\" at the cluster scope"
level=error ts=2020-09-24T14:15:38.920Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:362: Failed to list *v1.Service: services is forbidden: User \"system:serviceaccount:brcm-prometheus1:prometheus\" cannot list resource \"services\" in API group \"\" at the cluster scope"
level=error ts=2020-09-24T14:15:53.579Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:449: Failed to list *v1.Node: nodes is forbidden: User \"system:serviceaccount:brcm-prometheus1:prometheus\" cannot list resource \"nodes\" in API group \"\" at the cluster scope"
level=error ts=2020-09-24T14:16:01.056Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:361: Failed to list *v1.Endpoints: endpoints is forbidden: User \"system:serviceaccount:brcm-prometheus1:prometheus\" cannot list resource \"endpoints\" in API group \"\" at the cluster scope"
level=error ts=2020-09-24T14:16:09.632Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:363: Failed to list *v1.Pod: pods is forbidden: User \"system:serviceaccount:brcm-prometheus1:prometheus\" cannot list resource \"pods\" in API group \"\" at the cluster scope"
level=error ts=2020-09-24T14:16:14.661Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:385: Failed to list *v1.Pod: pods is forbidden: User \"system:serviceaccount:brcm-prometheus1:prometheus\" cannot list resource \"pods\" in API group \"\" at the cluster scope"
level=error ts=2020-09-24T14:16:30.799Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:362: Failed to list *v1.Service: services is forbidden: User \"system:serviceaccount:brcm-prometheus1:prometheus\" cannot list resource \"services\" in API group \"\" at the cluster scope"
level=error ts=2020-09-24T14:16:48.497Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:449: Failed to list *v1.Node: nodes is forbidden: User \"system:serviceaccount:brcm-prometheus1:prometheus\" cannot list resource \"nodes\" in API group \"\" at the cluster scope"
level=error ts=2020-09-24T14:16:51.634Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:363: Failed to list *v1.Pod: pods is forbidden: User \"system:serviceaccount:brcm-prometheus1:prometheus\" cannot list resource \"pods\" in API group \"\" at the cluster scope"
level=error ts=2020-09-24T14:16:53.140Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:361: Failed to list *v1.Endpoints: endpoints is forbidden: User \"system:serviceaccount:brcm-prometheus1:prometheus\" cannot list resource \"endpoints\" in API group \"\" at the cluster scope"
level=error ts=2020-09-24T14:16:59.600Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:385: Failed to list *v1.Pod: pods is forbidden: User \"system:serviceaccount:brcm-prometheus1:prometheus\" cannot list resource \"pods\" in API group \"\" at the cluster scope"
level=error ts=2020-09-24T14:17:13.092Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:362: Failed to list *v1.Service: services is forbidden: User \"system:serviceaccount:brcm-prometheus1:prometheus\" cannot list resource \"services\" in API group \"\" at the cluster scope"
level=error ts=2020-09-24T14:17:18.558Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:449: Failed to list *v1.Node: nodes is forbidden: User \"system:serviceaccount:brcm-prometheus1:prometheus\" cannot list resource \"nodes\" in API group \"\" at the cluster scope"
level=error ts=2020-09-24T14:17:21.722Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:363: Failed to list *v1.Pod: pods is forbidden: User \"system:serviceaccount:brcm-prometheus1:prometheus\" cannot list resource \"pods\" in API group \"\" at the cluster scope"
des is forbidden: User \"system:serviceaccount:brcm-prometheus1:prometheus\" cannot list resource \"nodes\" in API group \"\" at the cluster scope"
level=error ts=2020-09-24T14:15:12.298Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:361: Failed to list *v1.Endpoints: endpoints is forbidden: User \"system:serviceaccount:brcm-prometheus1:prometheus\" cannot list resource \"endpoints\" in API group \"\" at the cluster scope"
level=error ts=2020-09-24T14:15:23.043Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:363: Failed to list *v1.Pod: pods is forbidden: User \"system:serviceaccount:brcm-prometheus1:prometheus\" cannot list resource \"pods\" in API group \"\" at the cluster scope"
level=error ts=2020-09-24T14:15:25.950Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:385: Failed to list *v1.Pod: pods is forbidden: User \"system:serviceaccount:brcm-prometheus1:prometheus\" cannot list resource \"pods\" in API group \"\" at the cluster scope"
level=error ts=2020-09-24T14:15:38.920Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:362: Failed to list *v1.Service: services is forbidden: User \"system:serviceaccount:brcm-prometheus1:prometheus\" cannot list resource \"services\" in API group \"\" at the cluster scope"
level=error ts=2020-09-24T14:15:53.579Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:449: Failed to list *v1.Node: nodes is forbidden: User \"system:serviceaccount:brcm-prometheus1:prometheus\" cannot list resource \"nodes\" in API group \"\" at the cluster scope"
level=error ts=2020-09-24T14:16:01.056Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:361: Failed to list *v1.Endpoints: endpoints is forbidden: User \"system:serviceaccount:brcm-prometheus1:prometheus\" cannot list resource \"endpoints\" in API group \"\" at the cluster scope"

```

**Anything else we need to know?**:

**Comment by JohnRusk** [comment] 2020-09-24 23:43
Nice, @vperi1730.  I've just logged something very similar.  Maybe the stuff I logged in #3544 would be one way to do what you're looking for.  I logged it separately because you're looking specifically to use (only?) RoleBinding, whereas I'm suggesting splitting the existing ClusterRoleBinding - keeping some things at cluster level and moving others to namespace level.

**Comment by vperi1730** [comment] 2020-09-28 10:08
Can someone answer to our question and help us.

**Comment by vperi1730** [comment] 2020-10-12 07:39
Team - Could you please help us and let us know on this ask.

**Comment by coderanger** [comment] 2020-10-12 08:02
I think we can close this as a duplicate of #3544.

**Comment by paulfantom** [comment] 2020-10-13 10:39
Closed as a duplicate

**Closed** 2020-10-13 10:39 UTC
Labels: kind/support
