### ISSUE TITLE
Prometheus remote storage - not setting send_interval 

### ISSUE THREAD

**Issue by raz08** [prometheus-operator/prometheus-operator#3898] opened 2021-03-05 14:32 UTC
I'm trying to set remote storage write send_interval with Prometheus operator. But it is not getting reflected in Prometheus Configuration.

`  remoteWrite:
    - url: {{ required "please provide remote write url" .Values.prometheus.remoteStorage.remoteWriteUrl }}
      metadataConfig:
        sendInterval: 5m
  remoteRead:
    - url: {{ required "please provide remote read url" .Values.prometheus.remoteStorage.remoteReadUrl }}
      metadataConfig:
        sendInterval: 5m
`

prometheus-operator:v0.40.0
prometheus:v2.20.0
prometheus-config-reloader:v0.40.0
configmap-reload:v0.0.1

I don't see sendInterval in API doc of remoteWriteSpec : 
https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#remotewritespec

Is it supported? or Am I missing anything.  If it is not supported then is there plan to support.

**Comment by simonpasquier** [comment] 2021-03-08 11:29
Closed as a duplicate of #3889. The operator doesn't support `metadata_config` for remote write.

**Closed by simonpasquier** 2021-03-08 11:29 UTC

**Comment by gabrieleiannetti** [comment] 2023-06-21 14:22
@raz08 thanks for version hint, the same Prometheus version we are using atm and I could not found any hint on the Prometheus docs which version is required for that feature...

Best
Gabriele
