### ISSUE TITLE
Operator automatically adds namespace selector to AlertManager routes

### ISSUE THREAD

**Issue by younglin-db** [prometheus-operator/prometheus-operator#4289] opened 2021-09-28 06:13 UTC
**What did you do?**

I added an AlertManagerConfig with matchers, and I expected it to match anything with those matchers. I then discovered that a matcher with namespace was automatically added, as documented here: https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#route. 

I'm wondering why this is the case? For a single AlertManager instance, how can we configure routes that match separate namespaces? This is necessary as we'll be using one AM for multiple teams.

**Did you expect to see some different?**

Not adding an automatic namespace matcher.

**Comment by simonpasquier** [comment] 2021-09-28 09:34
Duplicate of #3737. TL;DR: the initial objective of AlertmanagerConfig CRD was to allow namespace owners to setup their own alerting routes and the namespace matcher for first-level routes ensures that alerts from a given namespace are routed to the correct team.

The plan is to for support a global AlertmanagerConfig for the base configuration and work is in progress (see #4220).

**Closed by simonpasquier** 2021-09-28 09:34 UTC
Labels: kind/support
