### ISSUE TITLE
Add support for web configuration to the ThanosRuler CRD

### ISSUE THREAD

**Issue by mhamzahkhan** [prometheus-operator/prometheus-operator#6157] opened 2023-12-11 15:46 UTC
**What is missing?**

As the ThanosRuler CRD doesn't allow the configuration of TLS for the Web Server at the moment, we were trying to use the additionalArgs to specify the http.config flag with a configuration that points to the TLS certificates.

While this works, the config-reloader breaks, as it's still using --reload-url=http://127.0.0.1:10902/-/reload, which returns:

level=error ts=2023-12-11T09:45:54.090853004Z caller=runutil.go:100 msg="function failed. Retrying in next tick" err="trigger reload: received non-200 response: 400 Bad Request; have you set `--web.enable-lifecycle` Prometheus flag?"

This appears to be fixed if we edit the statefulset manually and set the reload-url to https instead, but that change is reverted by the operator.

**Why do we need it?**

As the operator currently doesn't have any option to configure TLS on the Web UI port of ThanosRuler, it would be useful to be able to override the reload-url, so we can configure TLS using additionalArgs with the http.config option of thanos-ruler.

**Comment by simonpasquier** [comment] 2023-12-11 16:04
Rather than exposing the reload URL, I'd add `.spec.web` in the ThanosRuler CRD too.

**Comment by jamshidi799** [comment] 2024-01-15 19:32
I'm willing to work on this issue, can I assign it to myself?

**Comment by simonpasquier** [comment] 2024-01-16 08:58
@jamshidi799 feel free to submit a PR. Claiming your interest in the issue is enough :)

**Closed** 2024-03-13 16:31 UTC
Labels: help wanted, kind/feature, good first issue
