### ISSUE TITLE
Allow default alertmanager.yaml be to configured by AlertManagerConfig rather than Secret.

### ISSUE THREAD

**Issue by antoniordz96** [prometheus-operator/prometheus-operator#4340] opened 2021-10-18 22:13 UTC
**What is missing?**

Disable operator from creating null receiver below when secret `alertmanager-<alertmanager-name>` is missing:
```
route:
  receiver: "null"
receivers:
- name: "null"
templates: []
```
---
Currently the Prometheus operator will by default generate an `alertmanager.yaml` from the secret `alertmanager-<alertmanager-name>`. If this secret is not found then it will generate the configuration above. The way we setup our environment we are prevented from creating secrets, so we defined our alertManager configuration via the  AlertManagerConfig. 

This works but my generated alertmanager config still has the null receiver defined.

Example: 
```
global:
  resolve_timeout: 5m
  http_config: {}
  smtp_hello: localhost
  smtp_require_tls: true
  pagerduty_url: https://events.pagerduty.com/v2/enqueue
  opsgenie_api_url: https://api.opsgenie.com/
  wechat_api_url: https://qyapi.weixin.qq.com/cgi-bin/
  victorops_api_url: https://alert.victorops.com/integrations/generic/20131114/alert/
route:
  receiver: "null"
  routes:
  - receiver: application-monitoring-main-config
    group_by:
    - namespace
    - alertname
    - service
    match:
      namespace: monitoring
    continue: true
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 12h
receivers:
- name: "null"
- name: application-monitoring-main-config
  pagerduty_configs:
  - {{ DATA }}
templates: []
```

I would like the null receiver to be removed and the default configuration be what I defined in my AlertManagerConfig

**Why do we need it?**
Avoid operator spitting out logs about missing secret and define alertmanager configuration only via the AlertManagerConfig. 

**Environment**: Openshift

**Prometheus Operator version:**  0.47.0

**Comment by simonpasquier** [comment] 2021-10-19 08:32
I think this is a duplicate of https://github.com/prometheus-operator/prometheus-operator/issues/3737. Closing it but feel free to reopen if that's not the case.

**Closed by simonpasquier** 2021-10-19 08:32 UTC
Labels: kind/feature

**Comment by infa-mlagad** [comment] 2022-09-20 11:02
Hi @antoniordz96  , were you able to fix this? I am facing exactly same issue. 
Also where did you define global: parameters. I see there no option for global in alertmanagerconfig object. So i had to define it in alertmanager secret. But this is adding those **null** parameters as well in the config.

**Comment by mojiodevops** [comment] 2023-09-11 21:34
Global are defined in values.yml 
alertmanager:
  config:
    global:
      resolve_timeout: 5m


> Hi @antoniordz96 , were you able to fix this? I am facing exactly same issue. Also where did you define global: parameters. I see there no option for global in alertmanagerconfig object. So i had to define it in alertmanager secret. But this is adding those **null** parameters as well in the config.
