### ISSUE TITLE
Installation of prometheus-operator chart fails (timed out). Possibly due to unreachable api-server?

### ISSUE THREAD

**Issue by bhandari8sujit** [prometheus-operator/prometheus-operator#3336] opened 2020-07-15 17:37 UTC
**What happened?**
Installation of prometheus-operator chart fails (timed out). Possibly due to unreachable api-server?

**Did you expect to see something different?**
A clean installation was expected.

**How to reproduce it (as minimally and precisely as possible)**:

kubectl apply -f https://raw.githubusercontent.com/coreos/prometheus-operator/release-0.38/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml -n monitoring
kubectl apply -f https://raw.githubusercontent.com/coreos/prometheus-operator/release-0.38/example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml -n monitoring
kubectl apply -f https://raw.githubusercontent.com/coreos/prometheus-operator/release-0.38/example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml -n monitoring
kubectl apply -f https://raw.githubusercontent.com/coreos/prometheus-operator/release-0.38/example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml -n monitoring
kubectl apply -f https://raw.githubusercontent.com/coreos/prometheus-operator/release-0.38/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml -n monitoring
kubectl apply -f https://raw.githubusercontent.com/coreos/prometheus-operator/release-0.38/example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml -n monitoring

`helm install prometheus-operator stable/prometheus-operator -n monitoring --set prometheusOperator.createCustomResource=false --atomic --wait --debug`

**Environment**
Baremetal - Using Kubeadm

![Screenshot from 2020-07-15 14-24-21](https://user-images.githubusercontent.com/20126155/87576647-1194ef00-c6a8-11ea-8f6a-80239848069c.png)

* Prometheus Operator version:
stable/prometheus-operator

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

* Helm version information:
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}

* Kubernetes cluster kind:

    Baremetal - Using Kubeadm

* Manifests: N/A

```
N/A
```

* Prometheus Operator Logs:
Output of `kubectl logs prometheus-operator-admission-create-fmqdj -n monitoring`
```
{"err":"Get https://10.96.0.1:443/api/v1/namespaces/monitoring/secrets/prometheus-operator-admission: dial tcp 10.96.0.1:443: i/o timeout","level":"fatal","msg":"error getting secret","source":"k8s/k8s.go:104","time":"2020-07-15T16:22:02Z"}
```

**Anything else we need to know?**: No

**Comment by brancz** [comment] 2020-07-16 04:41
@vsliouniaev looks like this might have something to do with the admission webhook. As you also know the helm chart better, could you have a look at this?

**Comment by piraces** [comment] 2020-07-16 13:21
Experiencing the same issue here...

First I was getting this error:
```
Error: failed to create resource: Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": Post https://prometheus-operator-operator.monitoring.svc:443/admission-prometheusrules/validate?timeout=30s: dial tcp 192.168.0.166:443: connect: connection refused
```

Then it changed to this:
```
Error: UPGRADE FAILED: failed to create resource: Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": Post https://prometheus-operator-operator.monitoring.svc:443/admission-prometheusrules/validate?timeout=30s: x509: certificate signed by unknown authority (possibly because of "x509: ECDSA verification failure" while trying to verify candidate authority certificate "serial:6560999753765558533674002738516503862")
```

**Comment by vsliouniaev** [comment] 2020-07-17 05:30
@bhandari8sujit 
You're correct - sounds like the issue is caused by unreachable api server when the helm chart is trying to create some certificates for admission webhooks:
```
kubectl logs prometheus-operator-admission-create-fmqdj -n monitoring
{"err":"Get https://10.96.0.1:443/api/v1/namespaces/monitoring/secrets/prometheus-operator-admission: dial tcp 1
```

Unfortunately helm is notoriously poor at fixing issues that happen on first install. So the only thing I can think of is to purge and start again.

@piraces 
Your issue does not sound the same, however it does suggest that your api server is having an issue reaching prometheus-operator. I've seen the first error caused by a firewall on GKE before, I've also seen it due to flaky networking happening.

Your second error sounds like the helm chart failed to install correctly, in which case, I would advise the same thing - purge the chart and try it again.

**Comment by piraces** [comment] 2020-07-17 07:42
Thanks @vsliouniaev , purging the chart and trying again solved my issue. Sorry for the noise...

**Comment by bhandari8sujit** [comment] 2020-07-21 21:24
Thanks @vsliouniaev - I'll will try purging the chart

**Comment by simonpasquier** [comment] 2020-10-13 09:19
Closing since it's related to the Helm charts.

**Closed by simonpasquier** 2020-10-13 09:19 UTC
Labels: kind/bug
