### ISSUE TITLE
Support mutating PrometheusRules with partial_response_strategy

### ISSUE THREAD

**Issue by aiyengar2** [prometheus-operator/prometheus-operator#3648] opened 2020-11-05 02:18 UTC
**What happened?**
Can't add `partial_response_strategy` to a PrometheusRule when validation is enabled.

**Did you expect to see something different?**
Yes, it's a valid field.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy Prometheus Operator onto a Kubernetes cluster with [a MutatingWebhookConfiguration pointing to `/admission-prometheusrules/mutate`](https://github.com/prometheus-community/helm-charts/blob/72672f06a97fd60771f487fd40b7f4f05e2bc8c7/charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/mutatingWebhookConfiguration.yaml#L1-L33). This can be done by deploying [`kube-prometheus-stack`](https://github.com/prometheus-community/helm-charts/tree/72672f06a97fd60771f487fd40b7f4f05e2bc8c7/charts/kube-prometheus-stack).

Try to update a PrometheusRule and receive something like the following in the Prometheus Operator logs:
```
level=info ts=2020-11-03T01:35:38.709271395Z caller=admission.go:206 component=admissionwebhook msg="Invalid rule" err="yaml: unmarshal errors:\n line 1: field partial_response_strategy not found in type rulefmt.RuleGroup"
```

**Environment**: Kubernetes

* Prometheus Operator version: v0.38.1

    `coreos/prometheus-operator:v0.38.1`
    

* Kubernetes version information:

    `Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}`
    

* Kubernetes cluster kind:

   `RKE cluster deployed by Rancher`
    insert how you created your cluster: kops, bootkube, etc.

* Manifests:

```
```

* Prometheus Operator Logs:

```
level=info ts=2020-11-03T01:35:38.709271395Z caller=admission.go:206 component=admissionwebhook msg="Invalid rule" err="yaml: unmarshal errors:\n line 1: field partial_response_strategy not found in type rulefmt.RuleGroup"
```

**Anything else we need to know?**:

Original Issue: https://github.com/rancher/rancher/issues/29911

Issue in Helm Chart: https://github.com/prometheus-community/helm-charts/issues/297

Since this is a field that is related to Prometheus Operator and not introduced in Prometheus, maybe https://github.com/prometheus-operator/prometheus-operator/blob/b4ecadf26f10acb14fcd87c5d288e94e2eaced14/pkg/admission/admission.go#L211-L220 should remove the partial_response_strategy field before trying to validate the rule via `rulefmt.Parse(rules.Spec.Raw)`?

**Comment by paulfantom** [comment] 2020-11-23 13:09
This is not a bug since `partial_response_strategy` is not a prometheus rule group field. This is an additional field used by thanos. Changing to feature request.

**Comment by vsliouniaev** [comment] 2021-01-20 15:45
Seems like this is a bug, since the field is included in the API spec for the CRD, but then fails validation if it is used. https://github.com/prometheus-operator/prometheus-operator/blob/master/pkg/apis/monitoring/v1/types.go#L1138

**Comment by simonpasquier** [comment] 2023-01-09 16:23
The bug should be resolved in the latest versions of the operator.

**Closed by simonpasquier** 2023-01-09 16:23 UTC
Labels: help wanted, kind/feature
