### ISSUE TITLE
Version 0.52.0 dropped the app label from the statefulset but is still in the service selector causing no endpoint in the service 

### ISSUE THREAD

**Issue by primeroz** [prometheus-operator/prometheus-operator#4408] opened 2021-11-16 14:31 UTC
**What happened?**
I upgraded to 0.52.1 , in 0.52.0 the `app` label was dropped from the statefulset for prometheus and alertmanager but is still in the service selector causing no endpoint in the service 

I did delete the service forcing the operator to recreate it but it came back with the app label in the selector

```
  selector:
    app: prometheus
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: kube-prometheus
    prometheus: k8s
```

**Did you expect to see something different?**
I expected the app label to be removed from the selector 
**How to reproduce it (as minimally and precisely as possible)**:

**Environment**

* Prometheus Operator version:
0.52.1
* Kubernetes version information:
GitVersion:"v1.19.13-eks-8df270"
* Kubernetes cluster kind:
EKS
* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by fpetkovski** [comment] 2021-11-16 14:38
Hi @primeroz, does this issue exist in both 0.52.0 and 0.52.1, or just in 0.52.1?

**Comment by primeroz** [comment] 2021-11-16 14:39
I have _only_ tested on 0.52.1 , i was on 0.51.1 and jumped directly to 0.52.1 

I can try on 0.52.0 as soon as i am finished with something else here

**Comment by primeroz** [comment] 2021-11-16 15:23
@fpetkovski yeah this is happening as well on 0.52.0

**Comment by fpetkovski** [comment] 2021-11-16 15:28
Thanks for double checking this. I wonder if this is a kube-prometheus or a prometheus-operator issue. I'll need some time to track down the issue

**Comment by primeroz** [comment] 2021-11-16 15:31
Sure i am just downgrading in the meantime ! 

thanks

**Comment by slashpai** [comment] 2021-11-16 18:40
I created a fresh minikube cluster and spinned up the monitoring stack using kube-prometheus main branch. I was able to get the stack up, its using `0.52.0` version of prometheus-operator. I think this would problem while upgrading from one version to another since existing label won't be removed? I am trying to test that


```bash
░▒▓    ~/gi/s/kube-prometheus  on   main *1  k get sts --show-labels
NAME                READY   AGE     LABELS
alertmanager-main   3/3     5m32s   alertmanager=main,app.kubernetes.io/component=alert-router,app.kubernetes.io/name=alertmanager,app.kubernetes.io/part-of=kube-prometheus,app.kubernetes.io/version=0.23.0
prometheus-k8s      2/2     5m28s   app.kubernetes.io/component=prometheus,app.kubernetes.io/name=prometheus,app.kubernetes.io/part-of=kube-prometheus,app.kubernetes.io/version=2.31.1,operator.prometheus.io/name=k8s,operator.prometheus.io/shard=0,prometheus=k8s

░▒▓    ~/gi/s/kube-prometheus  on   main *1  k get pods --show-labels
NAME                                   READY   STATUS    RESTARTS   AGE     LABELS
alertmanager-main-0                    2/2     Running   0          5m52s   alertmanager=main,app.kubernetes.io/component=alert-router,app.kubernetes.io/instance=main,app.kubernetes.io/managed-by=prometheus-operator,app.kubernetes.io/name=alertmanager,app.kubernetes.io/part-of=kube-prometheus,app.kubernetes.io/version=0.23.0,controller-revision-hash=alertmanager-main-6d76d976c6,statefulset.kubernetes.io/pod-name=alertmanager-main-0
alertmanager-main-1                    2/2     Running   0          5m52s   alertmanager=main,app.kubernetes.io/component=alert-router,app.kubernetes.io/instance=main,app.kubernetes.io/managed-by=prometheus-operator,app.kubernetes.io/name=alertmanager,app.kubernetes.io/part-of=kube-prometheus,app.kubernetes.io/version=0.23.0,controller-revision-hash=alertmanager-main-6d76d976c6,statefulset.kubernetes.io/pod-name=alertmanager-main-1
alertmanager-main-2                    2/2     Running   0          5m52s   alertmanager=main,app.kubernetes.io/component=alert-router,app.kubernetes.io/instance=main,app.kubernetes.io/managed-by=prometheus-operator,app.kubernetes.io/name=alertmanager,app.kubernetes.io/part-of=kube-prometheus,app.kubernetes.io/version=0.23.0,controller-revision-hash=alertmanager-main-6d76d976c6,statefulset.kubernetes.io/pod-name=alertmanager-main-2
blackbox-exporter-6798fb5bb4-9m8cz     3/3     Running   0          5m52s   app.kubernetes.io/component=exporter,app.kubernetes.io/name=blackbox-exporter,app.kubernetes.io/part-of=kube-prometheus,app.kubernetes.io/version=0.19.0,pod-template-hash=6798fb5bb4
grafana-7f4665cb5f-5dxsw               1/1     Running   0          5m51s   app.kubernetes.io/component=grafana,app.kubernetes.io/name=grafana,app.kubernetes.io/part-of=kube-prometheus,app.kubernetes.io/version=8.2.3,pod-template-hash=7f4665cb5f
kube-state-metrics-68c99d589b-vcspt    3/3     Running   0          5m51s   app.kubernetes.io/component=exporter,app.kubernetes.io/name=kube-state-metrics,app.kubernetes.io/part-of=kube-prometheus,app.kubernetes.io/version=2.2.4,pod-template-hash=68c99d589b
node-exporter-px6md                    2/2     Running   0          5m50s   app.kubernetes.io/component=exporter,app.kubernetes.io/name=node-exporter,app.kubernetes.io/part-of=kube-prometheus,app.kubernetes.io/version=1.2.2,controller-revision-hash=5d5f98684c,pod-template-generation=1
prometheus-adapter-7dc46dd46d-vwmln    1/1     Running   0          5m50s   app.kubernetes.io/component=metrics-adapter,app.kubernetes.io/name=prometheus-adapter,app.kubernetes.io/part-of=kube-prometheus,app.kubernetes.io/version=0.9.1,pod-template-hash=7dc46dd46d
prometheus-adapter-7dc46dd46d-x7gh8    1/1     Running   0          5m50s   app.kubernetes.io/component=metrics-adapter,app.kubernetes.io/name=prometheus-adapter,app.kubernetes.io/part-of=kube-prometheus,app.kubernetes.io/version=0.9.1,pod-template-hash=7dc46dd46d
prometheus-k8s-0                       2/2     Running   0          5m48s   app.kubernetes.io/component=prometheus,app.kubernetes.io/instance=k8s,app.kubernetes.io/managed-by=prometheus-operator,app.kubernetes.io/name=prometheus,app.kubernetes.io/part-of=kube-prometheus,app.kubernetes.io/version=2.31.1,controller-revision-hash=prometheus-k8s-7d994f449b,operator.prometheus.io/name=k8s,operator.prometheus.io/shard=0,prometheus=k8s,statefulset.kubernetes.io/pod-name=prometheus-k8s-0
prometheus-k8s-1                       2/2     Running   0          5m48s   app.kubernetes.io/component=prometheus,app.kubernetes.io/instance=k8s,app.kubernetes.io/managed-by=prometheus-operator,app.kubernetes.io/name=prometheus,app.kubernetes.io/part-of=kube-prometheus,app.kubernetes.io/version=2.31.1,controller-revision-hash=prometheus-k8s-7d994f449b,operator.prometheus.io/name=k8s,operator.prometheus.io/shard=0,prometheus=k8s,statefulset.kubernetes.io/pod-name=prometheus-k8s-1
prometheus-operator-6b6b5dbb8f-qfsn2   2/2     Running   0          6m7s    app.kubernetes.io/component=controller,app.kubernetes.io/name=prometheus-operator,app.kubernetes.io/part-of=kube-prometheus,app.kubernetes.io/version=0.52.0,pod-template-hash=6b6b5dbb8f

```

**Comment by primeroz** [comment] 2021-11-16 19:29
@slashpai so your service selector does not have the app label in it ?

I did try deleting the service post upgrade and it was recreated with the app label in the selector so it did not look like an upgrade issue to me but still could be.

Tomorrow I will try reproduce it on a local cluster as well ... I did check for any local customisation on my side but I could not really find anything causing this

**Comment by slashpai** [comment] 2021-11-16 19:42
In kube-prometheus app label was removed much earlier AFAIK so those manifests should not have those. I rechecked again I couldn't find, I will check again tomorrow

**Comment by primeroz** [comment] 2021-11-17 09:18
It turns out it was my fault .

I am running kube-prometheus v0.9.0 which still have the app label in the selector but i upgraded the version of the prometheus-operator and that's why it broke. 

I thought the service was created by the operator but it obviously is not 

https://github.com/prometheus-operator/kube-prometheus/blob/v0.9.0/jsonnet/kube-prometheus/components/prometheus.libsonnet#L107

I will keep delete the app label in my jsonnet for now and re-upgrade to 0.52.1 

Do you reckon i sohuld create an issue in kube-prometheus to maybe get a point release of 0.9 or just wait for 0.10 to be released eventually ? 

feel free to close this

**Comment by fpetkovski** [comment] 2021-11-17 09:24
Thanks for double checking on your side, it makes sense that the issue is not caused by PO itself but by the way it's configured. 

If I understood @slashpai correctly, kube-prometheus dropped the app label a while back. I also don't see it in the 0.9 release branch: https://github.com/prometheus-operator/kube-prometheus/blob/release-0.9/jsonnet/kube-prometheus/components/prometheus-operator.libsonnet#L16

Could you point us to the line which in the git repo that injects this label?

**Comment by slashpai** [comment] 2021-11-17 09:27
https://github.com/prometheus-operator/kube-prometheus/blob/release-0.9/jsonnet/kube-prometheus/components/prometheus.libsonnet#L107

its still there in selector, we would want a new kube-prometheus release since its removed in main branch?

**Comment by paulfantom** [comment] 2021-11-17 09:36
Closing as this turned out not to be an operator issue.
FYI kube-prometheus 0.10.0 is just around the corner :)

**Closed by paulfantom** 2021-11-17 09:36 UTC
Labels: kind/bug

**Comment by primeroz** [comment] 2021-11-17 10:07
thanks !
