### ISSUE TITLE
PVC Cleanup

### ISSUE THREAD

**Issue by Abhishek2590** [prometheus-operator/prometheus-operator#4134] opened 2021-06-25 13:21 UTC
Hi Team,

I'm raising this issue to understand how we can perform the cleanup of PVC, is there any standard approach that I need to follow in order to do the cleanup?

**Comment by paulfantom** [comment] 2021-06-30 09:50
Closing as this is a duplicate of existing discussion.

Answered in https://github.com/prometheus-operator/prometheus-operator/discussions/4133#discussioncomment-942449

**Closed by paulfantom** 2021-06-30 09:50 UTC
