### ISSUE TITLE
The CustomResourceDefinition "prometheuses.monitoring.coreos.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes

### ISSUE THREAD

**Issue by jithinjks** [prometheus-operator/prometheus-operator#4355] opened 2021-10-31 11:45 UTC
**What happened?**

**Did you expect to see something different?**

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    
    

* Kubernetes version information:

    `kubectl version`
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.20-eks-8c579e", GitCommit:"8c579edfc914f013ff48b2a2b2c1308fdcacc53f", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:13Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind:

Using EKS Cluster

* Manifests:

```
Used this guide to install 
https://grafana.com/docs/grafana-cloud/quickstart/prometheus_operator/
Bundle yml : kubectl apply -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/master/bundle.yaml
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by jim-barber-he** [comment] 2021-11-01 02:17
I have the same problem on a kOps created cluster using Kubernetes 1.22.3.
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:41:28Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:35:25Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
```
And trying to install it:
```
$ kubectl apply -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/master/example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
The CustomResourceDefinition "prometheuses.monitoring.coreos.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
```

**Comment by slashpai** [comment] 2021-11-01 02:51
Can you try with `kubectl create`. The issue is due to large annotation size which will be issue for `kubectl apply` since it stores last applied config.

**Comment by jim-barber-he** [comment] 2021-11-01 02:53
It works with `create`.
```
$ kubectl create -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/master/example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
customresourcedefinition.apiextensions.k8s.io/prometheuses.monitoring.coreos.com created
```

It fails with `apply` even if the CRD didn't previously exist.

**Comment by slashpai** [comment] 2021-11-01 03:34
`kubectl apply` will store `kubernetes.io/last-applied-configuration` annotation even if we are creating a new resource :)

**Comment by paulfantom** [comment] 2021-11-01 08:22
Closing as this was fixed in https://github.com/prometheus-operator/prometheus-operator/pull/4349. Please reopen if you feel the fix is insufficient.

**Closed by paulfantom** 2021-11-01 08:23 UTC
Labels: kind/bug

**Comment by guusvw** [comment] 2021-11-02 12:47
@paulfantom 
Is using `kubectl create` instead of `kubectl apply` right now the best approach?
We're generating our monitoring stack based on `kube-prometheus` and applying those manifests in every pipeline run, this is now somehow blocked, because we would need to handle that edge-case differently and that just feels bad.

**Comment by paulfantom** [comment] 2021-11-02 17:11
@guusvw that's kubernetes restriction (as mentioned in https://github.com/prometheus-operator/prometheus-operator/issues/4355#issuecomment-955899678) and using `kubectl create` to apply CRDs [is considered a valid workaround by kubernetes-sigs](https://github.com/kubernetes-sigs/kubebuilder/issues/1140). FYI tools like argoCD have an internal logic to hangle such cases by removing and creating object if needed. However if you use only `kubectl` you need to put that logic into your tooling.

As for kube-prometheus, we can simplify things for you by moving CRDs to a separate directory in `manifests/` if that would help. Just file an issue in the project first :)

**Comment by jzelinskie** [comment] 2022-07-01 18:08
Apologies for resurrecting a closed issue. `create` works around this by not creating the annotation, but this annotation is necessary for some kubectl functionality, for example `--prune`.

While there's a [PR for upstream to add support for server-side prune](https://github.com/kubernetes/kubernetes/pull/110913), these are all simply workarounds to the fact that the annotation just shouldn't be that big. Is there something about reducing the size that makes it a non-trivial problem? Issues for repeatedly cropping up seems like a pretty good indication it needs to be addressed.

**Comment by jzelinskie** [comment] 2022-07-28 02:45
👋

It looks like the PR for server-side prune got closed upstream. I suppose that only leaves us with your suggestion to create a stripped-down version of the CRD. While somewhat unfortunate, that'd solve our use-case. Should I create a new issue for that? Also willing to do some legwork if need be.

**Comment by simonpasquier** [comment] 2022-07-28 13:50
https://github.com/prometheus-operator/prometheus-operator/pull/4937 is a quick hack. It would be good if you could test it.

**Comment by rufreakde** [comment] 2023-02-10 10:20
This is also important when you use a Delivery tool like argoCD for example.

**Comment by b-a-t** [comment] 2023-03-09 12:47
> This is also important when you use a Delivery tool like argoCD for example.

For ArgoCD since 2.5 version there is a solution https://blog.ediri.io/kube-prometheus-stack-and-argocd-25-server-side-apply-to-the-rescue

**Comment by relief-melone** [comment] 2023-09-26 11:09
> > This is also important when you use a Delivery tool like argoCD for example.
> 
> For ArgoCD since 2.5 version there is a solution https://blog.ediri.io/kube-prometheus-stack-and-argocd-25-server-side-apply-to-the-rescue

server side apply for me had the negative side effect that the application is always shown as out of sync :( has anyone had other fixes so far?

**Comment by ebuildy** [comment] 2023-09-27 23:11
The quick-win solution --> add / harcode argocd syncOptions annotations on desired CRDs. I can do a PR, this is quick and work very well.

**Comment by simonpasquier** [comment] 2023-09-28 06:32
@ebuildy is it a change that is desired for *all* ArgoCD users?

**Comment by ebuildy** [comment] 2023-09-28 11:41
yes, currently you cannot set this annotations only for CRDs, so the dirty fix is to put the annotation at application level, for all resources, which is very bad.

We could add for all CRDs:

``` 
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
    strategy.spinnaker.io/replace: 'true'
```

Or much better, move CRDs to another public Helm chart

**Comment by inca** [comment] 2023-10-17 18:28
Since `stripped-down-crds.yaml` is now part of the official release, it might be a good idea to complement this with `everything-else-except-crds.yaml` so that the users can set up the operators using those two with the ubiquitous `kubectl apply`.

**Comment by ganesh1255** [comment] 2024-11-13 10:05
Tried kubect create and kubect apply along with --server-side, still not working
