### ISSUE TITLE
Add hostAlias support in Prometheus CRD

### ISSUE THREAD

**Issue by ethernoy** [prometheus-operator/prometheus-operator#4298] opened 2021-10-01 07:37 UTC
**What is missing?**
hostAlias setting in Prometheus CRD

**Why do we need it?**
Prometheus can have external dependencies like remote Prometheus Receive endpoint or alertmanager. Adding hostAliases support in it can help in enabling routing

**Environment**

N/A

**Anything else we need to know?**:

I am glad to submit a PR for this :)

**Comment by PhilipGough** [comment] 2021-10-01 08:53
Duplicate of https://github.com/prometheus-operator/prometheus-operator/issues/3488?

**Comment by PhilipGough** [comment] 2021-10-01 08:55
Related to https://github.com/prometheus-operator/prometheus-operator/issues/3488 where there is already some discussion about adding this to both `AlertManager` and `ThanosRuler`

**Comment by PhilipGough** [comment] 2021-10-01 09:00
Based On @simonpasquier comment I think this would likely make sense. If you intend to work on it please take a look at and consider the discussion around https://github.com/prometheus-operator/prometheus-operator/pull/3944#issuecomment-810490119.

We will likely want to be consistent in the implementation how we add this to the components.

**Comment by simonpasquier** [comment] 2021-10-04 11:47
Thanks for following up @PhilipGough! Yes ideally the CRD should offer a way to inject arbitrary fields into the statefulset definition, just like we do with the `containers` field today.

**Closed** 2022-06-02 15:49 UTC
Labels: kind/feature
