### ISSUE TITLE
create poddisruptionbudget for statefulsets

### ISSUE THREAD

**Issue by juliantaylor** [prometheus-operator/prometheus-operator#4249] opened 2021-09-07 09:49 UTC
**What is missing?**

poddisruptionbudgets are important to avoid service downtimes during cluster management operations (like node draining). The operator should create these automatically as manually creating them is error prone as the selector labels for the statefulset are defined by the operator and cannot by dynamically added to a manually created pod disruption budget without needing to carefully validate this on each update.

podMetadata.labels cannot be used reliably as e.g. the `app.kubernetes.io/managed-by` label defined in the Prometheus podMetadata.labels is overwritten by the operator to its own value.
also adding pdb for configuration using shards is probably fragile as the selector labels are again operator defined and probably not part of the stable api

**Comment by simonpasquier** [comment] 2021-09-08 09:35
duplicate of #3917 ?

**Comment by paulfantom** [comment] 2021-11-03 12:32
Closing as dup of #3917.

**Closed by paulfantom** 2021-11-03 12:32 UTC
Labels: kind/feature
