### ISSUE TITLE
Add support for "hostPath" storage type

### ISSUE THREAD

**Issue by pbxqdown** [prometheus-operator/prometheus-operator#3858] opened 2021-02-21 00:02 UTC
**What is missing?**
Currently, only emptyDir and volumeClaimTemplate is supported by prometheus-operator. It is hard to mount local host volume 
**Why do we need it?**
On single node environment, it is not necessary to use PVC. It is not convenient and causes issue(i.e. for 2 replicas, we have to create 2 PVC and 2 PV for all pods)
If a hostPath option is provided, it would be very convenient to mount local directory for prometheus data persistence.

**Comment by rmartinez3** [comment] 2021-02-21 00:23
There was already a request asked here https://github.com/prometheus-operator/prometheus-operator/pull/1455 and don't think they will want to allow that. You are better off create storage class . PV to have pvc bind to.

**Comment by pbxqdown** [comment] 2021-02-21 00:31
I have tried PVC solution.  The problem is, prometheus-operator created 2 PVC(named pvc-prometheus-k8s-0 and pvc-prometheus-k8s-1) for 2 Pod. And only one of them is able to bind to the PV. 
Really messed up. Would be much convenient to use hostPath instead. I think many people run prometheus-operator on their single-node lab. So this is a valid use case.

**Comment by rmartinez3** [comment] 2021-02-21 00:37
You can create 2 persistent volume/claim before hand.  Which will then each promethues replica can consume  specifying the storage class name.

**Comment by rmartinez3** [comment] 2021-02-21 00:40
Or If you want to go the automatic provisioning route you can look at csi/storage local solutions to do the provisioning for you . But I think the easier route will be the manual setup route for now.

**Comment by pbxqdown** [comment] 2021-02-21 02:57
There are many MR/issues asking about how to use hostPath, the use cases do exist. Prometheus-operator is a base library of many upper level projects(e.g. kube-prometheus), i think it would be good to provide more customization(e.g. adding flags for containers, customize volume mounts, etc)

**Comment by rmartinez3** [comment] 2021-02-21 03:29
Though in your case. Why would you want two prometheus  instances pointing to the same host path. Since pinned on one node.  If data is corrupted then both prometheus instances will be down vs having independent volune/paths to have a HA promtheus cluster. As well I think one doesn't want two prometheus instances using the same volume.  I think this is the reason why prometheus operator avoided the use of host path.

**Comment by pbxqdown** [comment] 2021-02-21 06:36
Good point that statefulset should use 2 PVC. agree that data replication is necessary in this case.
But it may still be nice to have hostPath for single node environment, just like k8s did. anyway, i reduced replica to 1 and applied the PVC configuration. It only runs on my personal server and HA is not very necessary🙂

**Comment by paulfantom** [comment] 2021-02-22 07:53
I am closing this as a duplicate of #1455.

On a personal note, I can recommend using local-path-provisioner for this use case. With it, there is nothing to be changed in prometheus-operator as directories are created dynamically and there is no PV clash. This means storage is taken care of in kubernetes-native way without any hacks which would be necessary in the case of `hostPath`. You can take a look at such deployment at https://github.com/thaum-xyz/ankhmorpork/blob/master/apps/monitoring/manifests/prometheus/prometheus.yaml#L64-L74

**Closed by paulfantom** 2021-02-22 07:53 UTC
Labels: kind/feature
