### ISSUE TITLE
support skipping namespace match in generated route matchers

### ISSUE THREAD

**Issue by jjo** [prometheus-operator/prometheus-operator#4090] opened 2021-06-08 19:39 UTC
**What is missing?**

We should be able to skip default `namespace: <resource_namespace>` match entry in generated 1st route receiver.

**Why do we need it?**

We need this for cases where you e.g. have your `AlertmanagerConfig` resources in a
single namespace (e.g. "monitoring"), while using them to route _cluster-wide_
alerts (e.g. many cross-namespace same-team deployments),

**Environment**

* Prometheus Operator version:

`v0.48.1`

**Anything else we need to know?**:

About to submit PR :)

**Comment by paulfantom** [comment] 2021-06-09 09:12
Duplicate of #4033

**Closed by paulfantom** 2021-06-09 09:12 UTC
Labels: kind/feature
