### ISSUE TITLE
Add support for URL-parameters in ScrapeConfig

### ISSUE THREAD

**Issue by rhe89** [prometheus-operator/prometheus-operator#5717] opened 2023-06-27 12:08 UTC
**What is missing?**
Support scraping targets that require URL-parameters, see https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config and:

```
# Optional HTTP URL parameters.

params:
  [ <string>: [<string>], ...] ]
```

**Why do we need it?**
To support scraping more defined targets that can't be defined by only using metricsPath

**Environment**

* Prometheus Operator version:

    `prometheus-operator:v0.65.2`

**Comment by simonpasquier** [comment] 2023-06-27 12:17
Thanks for the report, this is a duplicate of #5592.

**Closed by simonpasquier** 2023-06-27 12:17 UTC
Labels: kind/feature
