### ISSUE TITLE
Applying CustomResourceDefinition "prometheuses.monitoring.coreos.com" fails: "metadata.annotations too long must have at most 262144 bytes"

### ISSUE THREAD

**Issue by ycd** [prometheus-operator/prometheus-operator#4367] opened 2021-11-04 13:23 UTC
**What happened?**

Applying a manifest failed with the following output:

```
The CustomResourceDefinition "prometheuses.monitoring.coreos.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
```

**Did you expect to see something different?**

Yes.

**How to reproduce it (as minimally and precisely as possible)**:

```sh
git clone https://github.com/prometheus-operator/kube-prometheus.git
kubectl apply -f manifests/setup/prometheus-operator-0prometheusCustomResourceDefinition.yaml
```

* Prometheus Operator version:

```
0.51.2
```

* Kubernetes version information:

```sh
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:52:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-0389ca3", GitCommit:"8a4e27b9d88142bbdd21b997b532eb6d493df6d2", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:46Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

AWS EKS.

* Manifests:

https://github.com/prometheus-operator/kube-prometheus/blob/31d86b794645315e8a0c270f7eed1d0231a68e29/manifests/setup/prometheus-operator-0prometheusCustomResourceDefinition.yaml#L1-L7

**Comment by fpetkovski** [comment] 2021-11-04 13:27
This is a duplicate of https://github.com/prometheus-operator/prometheus-operator/issues/4348. Can you see if using `kubectl create` fixes your problem?

**Comment by slashpai** [comment] 2021-11-04 13:36
Should we pin this issue for visibility of users facing similar issue?

**Comment by paulfantom** [comment] 2021-11-04 14:10
Closing as duplicate of #4348.

Great suggestion @slashpai :+1:  Issue pinned.

**Closed by paulfantom** 2021-11-04 14:10 UTC
Labels: kind/bug

**Comment by paulfantom** [comment] 2021-11-04 14:17
I pinned https://github.com/prometheus-operator/prometheus-operator/issues/4355 instead as it has a bit more explanation and title which should directly point people to the solution.
