### ISSUE TITLE
Prometheus web.yaml to include basic_auth_users configuration

### ISSUE THREAD

**Issue by fluzzykitten** [prometheus-operator/prometheus-operator#5650] opened 2023-06-07 16:05 UTC
There appears to be no way to set the `basic_auth_users` in the Prometheus web.yml (which enables configuration of basic auth in the web UI). 

https://prometheus.io/docs/prometheus/latest/configuration/https/
The Prometheus web.yml configuration allows the definition of 
- tls_server_config
- http_server_config
- basic_auth_users

https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#monitoring.coreos.com/v1.PrometheusWebSpec
But the `monitoring.coreos.com/v1` CRD for Prometheus only allows defining the:
- tlsConfig
- httpConfig

We would like the CRD to allow us to also configure the `basic_auth_users` Prometheus configuration to enable basic Auth on Prometheus. Thanks.

* Prometheus Operator version:
quay.io/prometheus-operator/prometheus-operator:v0.65.2

**Comment by simonpasquier** [comment] 2023-06-08 08:07
this is a duplicate of https://github.com/prometheus-operator/prometheus-operator/issues/4200 and https://github.com/prometheus-operator/prometheus-operator/pull/4942 tried to address but there are some issues with probes.

**Closed by simonpasquier** 2023-06-08 08:07 UTC
Labels: kind/feature
