### ISSUE TITLE
Prometheus pod didn't find prometheus.env.yaml for very first time.

### ISSUE THREAD

**Issue by amanjain08** [prometheus-operator/prometheus-operator#2847] opened 2019-11-06 06:11 UTC
**What happened?**

I have deployed Prometheus using prometheus-operator and saw Prometheus restarted just after fresh deployment because of prometheus.env.yaml wasn't available. But after 1st restart, prometheus is working fine and prometheus.env.yaml file is also available.

**Did you expect to see some different?**
prometheus.env.yaml should be available on fresh deployment.

**Environment**
Prometheus Version: 2.10.0

* Prometheus Operator version:

Prometheus Operator: 0.30.1

* Kubernetes version information:

    `Kubeadm version:
{Major:"1", Minor:"11", GitVersion:"v1.11.5", GitCommit:"753b2dbc622f5cc417845f0ff8a77f539a4213ea", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:30Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}`

* Prometheus Operator Logs:

```
ts=2019-11-06T05:00:06.655612628Z caller=main.go:169 msg="Starting Prometheus Operator version '0.30.0'."
level=info ts=2019-11-06T05:00:06.776512032Z caller=operator.go:213 component=alertmanageroperator msg="connection established" cluster-version=v1.11.5
level=info ts=2019-11-06T05:00:06.783715513Z caller=operator.go:391 component=prometheusoperator msg="connection established" cluster-version=v1.11.5
level=info ts=2019-11-06T05:00:06.908210612Z caller=operator.go:635 component=alertmanageroperator msg="CRD updated" crd=Alertmanager
level=info ts=2019-11-06T05:00:06.910736688Z caller=operator.go:1478 component=prometheusoperator msg="CRD updated" crd=Prometheus
level=info ts=2019-11-06T05:00:06.923338935Z caller=operator.go:1478 component=prometheusoperator msg="CRD updated" crd=ServiceMonitor
level=info ts=2019-11-06T05:00:06.967318873Z caller=operator.go:1478 component=prometheusoperator msg="CRD updated" crd=PrometheusRule
level=info ts=2019-11-06T05:00:09.938861708Z caller=operator.go:229 component=alertmanageroperator msg="CRD API endpoints ready"
level=info ts=2019-11-06T05:00:10.139312756Z caller=operator.go:184 component=alertmanageroperator msg="successfully synced all caches"
level=info ts=2019-11-06T05:00:16.183710414Z caller=operator.go:407 component=prometheusoperator msg="CRD API endpoints ready"
level=info ts=2019-11-06T05:00:16.885619027Z caller=operator.go:342 component=prometheusoperator msg="successfully synced all caches"
level=info ts=2019-11-06T05:09:46.739113927Z caller=operator.go:985 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
level=info ts=2019-11-06T05:09:47.465080422Z caller=operator.go:985 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
level=info ts=2019-11-06T05:09:47.550650998Z caller=operator.go:985 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
level=info ts=2019-11-06T05:09:47.780036122Z caller=operator.go:985 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
level=info ts=2019-11-06T05:09:47.881340146Z caller=operator.go:985 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
level=info ts=2019-11-06T05:09:49.985932146Z caller=operator.go:985 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
level=info ts=2019-11-06T05:09:50.197208989Z caller=operator.go:985 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
level=info ts=2019-11-06T05:09:50.447156319Z caller=operator.go:985 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
level=info ts=2019-11-06T05:09:50.573015181Z caller=operator.go:985 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
level=info ts=2019-11-06T05:10:15.154404862Z caller=operator.go:985 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
```

**Anything else we need to know?**:
Prometheus Logs 
```
level=info ts=2019-11-06T05:10:06.333Z caller=main.go:322 msg="Starting Prometheus" version="(version=2.10.0, branch=HEAD, revision=d20e84d0fb64aff2f62a977adc8cfb656da4e286)"
level=info ts=2019-11-06T05:10:06.333Z caller=main.go:323 build_context="(go=go1.12.5, user=root@a49185acd9b0, date=20190525-12:28:13)"
level=info ts=2019-11-06T05:10:06.333Z caller=main.go:324 host_details="(Linux 4.1.0-cl-7-amd64 #1 SMP Cumulus 4.1.33-1+cl3u22 (2019-08-06) x86_64 prometheus-k8s-0 (none))"
level=info ts=2019-11-06T05:10:06.333Z caller=main.go:325 fd_limits="(soft=1048576, hard=1048576)"
level=info ts=2019-11-06T05:10:06.333Z caller=main.go:326 vm_limits="(soft=unlimited, hard=unlimited)"
level=info ts=2019-11-06T05:10:06.335Z caller=main.go:645 msg="Starting TSDB ..."
level=info ts=2019-11-06T05:10:06.335Z caller=web.go:417 component=web msg="Start listening for connections" address=0.0.0.0:9090
level=info ts=2019-11-06T05:10:06.474Z caller=main.go:660 fs_type=9123683e
level=info ts=2019-11-06T05:10:06.475Z caller=main.go:661 msg="TSDB started"
level=info ts=2019-11-06T05:10:06.475Z caller=main.go:730 msg="Loading configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml
level=info ts=2019-11-06T05:10:06.475Z caller=main.go:514 msg="Stopping scrape discovery manager..."
level=info ts=2019-11-06T05:10:06.475Z caller=main.go:528 msg="Stopping notify discovery manager..."
level=info ts=2019-11-06T05:10:06.475Z caller=main.go:550 msg="Stopping scrape manager..."
level=info ts=2019-11-06T05:10:06.475Z caller=main.go:524 msg="Notify discovery manager stopped"
level=info ts=2019-11-06T05:10:06.475Z caller=main.go:510 msg="Scrape discovery manager stopped"
level=info ts=2019-11-06T05:10:06.475Z caller=manager.go:775 component="rule manager" msg="Stopping rule manager..."
level=info ts=2019-11-06T05:10:06.475Z caller=manager.go:781 component="rule manager" msg="Rule manager stopped"
level=info ts=2019-11-06T05:10:06.475Z caller=main.go:544 msg="Scrape manager stopped"
level=info ts=2019-11-06T05:10:06.494Z caller=notifier.go:530 component=notifier msg="Stopping notification manager..."
level=info ts=2019-11-06T05:10:06.494Z caller=main.go:714 msg="Notifier manager stopped"
level=error ts=2019-11-06T05:10:06.495Z caller=main.go:723 err="error loading config from \"/etc/prometheus/config_out/prometheus.env.yaml\": couldn't load configuration (--config.file=\"/etc/prometheus/config_out/prometheus.env.yaml\"): open /etc/prometheus/config_out/prometheus.env.yaml: no such file or directory"```

**Comment by brancz** [comment] 2020-01-06 07:12
This is still the case although continues to be a non issue in practice.

**Comment by carlosrmendes** [comment] 2020-03-20 18:16
@brancz I think is an issue. This causes an error on a fresh pod start that triggers a pod restart. The cause of pod restart is always an issue. If I have an alert for pod restarts and scale the prometheus replicas to more than 1 that alert will be triggered.

**Comment by brancz** [comment] 2020-03-23 06:28
Alerts for single restarts are an anti pattern. I agree it’s a cosmetic fault but not a functional one. If you would like to fix it, I’d be happy to review a PR :)

**Comment by angelovopsan** [comment] 2020-12-15 09:51
I can confirm this being an issue for https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack/12.8.0 running on EKS 1.18.9 (latest at the point of writing). Any pointers towards fixing the root cause?

**Comment by inoam** [comment] 2020-12-21 18:38
@angelovopsan this is indeed an issue, see: https://github.com/prometheus-operator/prometheus-operator/issues/3061
Community is waiting for someone to follow suggestion and open PR.

**Comment by inoam** [comment] 2020-12-21 18:39
#3061

**Comment by inoam** [comment] 2020-12-21 18:39
[https://github.com/prometheus-operator/prometheus-operator/issues/3061](url)

**Comment by paulfantom** [comment] 2021-06-07 18:58
Duplicate of #3061

**Closed by paulfantom** 2021-06-07 18:58 UTC
Labels: kind/bug
