### ISSUE TITLE
queries.active: permission denied

### ISSUE THREAD

**Issue by mohanagandlla** [prometheus-operator/prometheus-operator#3693] opened 2020-11-19 05:37 UTC
Hi I am facing this issue and the prometheus is from operator and that instace is previously working fine after almost 20 days now i am facing this issue (PV and PVC are bounded successful)

level=error ts=2020-11-19T05:32:16.299Z caller=query_logger.go:87 component=activeQueryTracker msg="Error opening query log file" file=/prometheus/queries.active err="open /prometheus/queries.active: permission denied"
panic: Unable to create mmap-ed active query log

I dont know why does it happen on previously it has worked fine but now it is showing this error.

**Comment by simonpasquier** [comment] 2020-11-19 08:38
For some reason the Prometheus process doesn't have permissions to write to the data directory. You might want to check the permissions/ownership of the volume. Closing as a duplicate of #3459.

**Closed by simonpasquier** 2020-11-19 08:38 UTC
Labels: kind/bug
