### ISSUE TITLE
Load Prometheus/AlertManager/ThanosRuler Web Server TLS certificates from file system

### ISSUE THREAD

**Issue by mhamzahkhan** [prometheus-operator/prometheus-operator#6156] opened 2023-12-11 14:50 UTC
**What is missing?**

At the moment, we are able to configure the GRPC server TLS certificates to be on the filesystem using the grpcServerTlsConfig.certFile and .keyFile options.

But for the Prometheus and AlertManager Web server configs (AlertmanagerWebSpec/PrometheusWebSpec) the TLS config (WebTLSConfig) only allows the use of TLS Certificates to be loaded from a K8S ConfigMap or a Secret. 

It would be handy to be able to load certificates from a location on a mounted file system, the same way we can for grpcServerTlsConfig for Prometheus and ThanosRuler.

ThanosRuler doesn't even have any options to configure the web server TLS options. 

**Why do we need it?**

Due to security requirements, we cannot store certificates and keys in K8S secrets. 

We use consul-template in an init container to get certificates from a Vault server, and put them into a mounted volume that is shared with other containers within the pod.

At the moment, as the operator doesn't allow using certificates from a mounted volume, we have to put an Nginx sidecar alongside our Prometheus/AlertManager and ThanosRuler deployments to get TLS working for the web UI.

Being able to configure Prometheus/Alertmanager/ThanosRuler to load the web server TLS certificates from a mounted volume means we would be able to get rid of the extra overhead of nginx.

**Comment by mhamzahkhan** [comment] 2023-12-11 15:37
> I'm not sure to understand where's the nginx sidecar is running and what it does exactly.

I apologise, I have updated the ticket with a bit more detail. Struggling to get my bearings today. 

I hope it makes more sense now?

**Comment by simonpasquier** [comment] 2023-12-11 16:00
Ok I got it now. This looks a valid use case to me.

**Comment by rootxrishabh** [comment] 2024-03-01 02:29
@simonpasquier I would like to work on this, can you please assign this to me?

**Comment by slashpai** [comment] 2024-03-01 02:45
> @simonpasquier I would like to work on this, can you please assign this to me?

Please feel free to work on the issue. Expressing interest in working on is enough 🙂

**Comment by yp969803** [comment] 2024-03-03 18:04
i raised a [pr](https://github.com/prometheus-operator/prometheus-operator/pull/6358)  for accessing certificates from volumes in prometheus

**Comment by yp969803** [comment] 2024-03-03 18:08
I think for "ThanosRuler doesn't even have any options to configure the web server TLS options" I should have to raise a another pr

**Comment by jabbrwcky** [comment] 2024-10-01 09:23
I have a similar use case, although I encountered it with the `thanos.grpcServerTlsConfig` configuration.

We are using cert-manager's csi-driver to issue certificates as mounted volumes (bypassing the need to create secrets and being able to issue per-pod certs)

It would be useful in general to allow for specifying file paths in the pod where tls-Secrets/Configmap references are used currently.

**Comment by simonpasquier** [comment] 2024-10-04 09:16
duplicate of #6358 which is implemented in v0.77.0.

**Closed by simonpasquier** 2024-10-04 09:16 UTC
Labels: help wanted, kind/feature
