### ISSUE TITLE
Alertmanager-operated not selecting pods on GKE and version 0.47.

### ISSUE THREAD

**Issue by Whyeasy** [prometheus-operator/prometheus-operator#4009] opened 2021-04-30 09:42 UTC
**What happened?**

When upgrading Prometheus-operator to version v0.47.0. The Alertmanager pods and statefulset is deleted and recreated, but it goes in to a crashloop. As the `alertmanager-operated` service doesn't select the pods and the endpoint is empty.

Errors in logs mention that it can't find any pods in the services and the pod restarts.

Labels on the service:
```
 labels:
    operated-alertmanager: "true"
```
Selector:
```
selector:
    app: alertmanager
```

Labels on pod:
```
        alertmanager: prometheus-kube-prometheus-alertmanager
        app: alertmanager
        app.kubernetes.io/instance: prometheus-kube-prometheus-alertmanager
        app.kubernetes.io/managed-by: prometheus-operator
        app.kubernetes.io/name: alertmanager
        app.kubernetes.io/version: v0.21.0
```

No annotations on the pod.

**Did you expect to see something different?**

That the endpoint is not empty and the pods would start.

**How to reproduce it (as minimally and precisely as possible)**:

Upgrade prometheus-operator to v0.47.0 on GKE version 1.19.8-gke.1600

**Environment**

* Prometheus Operator version:

    `quay.io/prometheus-operator/prometheus-operator:v0.47.0`

* Kubernetes version information:
 ```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.8-gke.1600", GitCommit:"4f6f69fd81ca8cb6962a2f7e1ed9c7880834cf71", GitTreeState:"clean", BuildDate:"2021-03-08T19:22:13Z", GoVersion:"go1.15.8b5", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

    GKE 1.19.8-gke.1600

**Anything else we need to know?**:

Prometheus-operator is installed via the helm-chart: https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack
And deployed via FluxV2/Helm-operator and Kustomize.

**Comment by Whyeasy** [comment] 2021-04-30 12:09
Issue is not related to labels or selectors. Seems an issue with the generated alertmanager yaml.

**Comment by chadlwilson** [comment] 2021-05-19 15:46
Hello @Whyeasy - I've also been hit by this same root cause on an operator `0.47` upgrade. Wonder if there is a reason you closed this (other than the original title being a bit misleading)?

It does seem like a bug to me if it's generating fields that aren't valid with respect to alertmanager config. There is no `follow_redirects` documented at https://prometheus.io/docs/alerting/latest/configuration/#http_config for `0.21.0`

Was your workaround to delete the `http_config: {}` entirely, perhaps? I wonder, since we set the below and can't simply remove this :-/

We set 
```
  alertmanager:
    config:
      global:
        slack_api_url: 'https://hooks.slack.com/REDACTED'
        http_config:
          proxy_url: 'http://my-proxy'
```

This looks to me like intended support for alertmanager `0.22` somewhere that breaks backward compat with `0.21`?
https://github.com/prometheus/alertmanager/pull/2551

**Comment by Whyeasy** [comment] 2021-05-19 18:03
Hi @chadlwilson,

The reason I closed it is because I got it working by removing `http_config: {}` in my alertmanager config. So for me the issue was "solved".

In your case it's indeed not a solution, as your proxy won't work. I would suggest to create a new issue (this time with a correct title 😉). 

Sorry I can't help you further!

**Comment by simonpasquier** [comment] 2021-05-20 14:28
Re-opening since it may be an issue for many users indeed.

**Closed** 2021-05-21 09:09 UTC
Labels: kind/bug

**Comment by chadlwilson** [comment] 2021-05-21 09:20
Thanks a lot @simonpasquier 👍
