### ISSUE TITLE
Fix package name in go.mod

### ISSUE THREAD

**Issue by MartinForReal** [prometheus-operator/prometheus-operator#3443] opened 2020-08-26 08:15 UTC
**What happened?**

I need to create servicemonitor object in my program. And when I try to compile my program. I found that the package name of operator is github.com/coreos/prometheus-operator

**Did you expect to see something different?**
I think it would be better if we renamed the whole project.

**Comment by MartinForReal** [comment] 2020-08-26 08:16
workaround: I can still use github.com/coreos/prometheus-operator as package name to import code

**Comment by simonpasquier** [comment] 2020-08-26 08:37
duplicate of https://github.com/prometheus-operator/prometheus-operator/issues/3393 :)

**Closed by simonpasquier** 2020-08-26 08:37 UTC
Labels: kind/bug
